name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_SECRET }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_SECRET }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_SECRET }}
      - name: Notify Discord
        if: always()
        run: |
            MESSAGE="🚀 **Déploiement de la production réussi !**\n🔗 URL de la démo : https://"
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"$MESSAGE\"}" \
              ${{ secrets.PROD_DISCORD_WEBHOOK_URL }}
